export const GET_AGENCIES_SUCCESS = 'GET_AGENCIES_SUCCESS';
export const GET_AGENCIES_FAILURE = 'GET_AGENCIES_FAILURE';
export const GET_AGENCIES_LOADING = 'GET_AGENCIES_LOADING';

export const GET_REGIONS_BY_AGENCY_SUCCESS = 'GET_REGIONS_BY_AGENCY_SUCCESS';
export const GET_REGIONS_BY_AGENCY_FAILURE = 'GET_REGIONS_BY_AGENCY_FAILURE';
export const GET_REGIONS_BY_AGENCY_LOADING = 'GET_REGIONS_BY_AGENCY_LOADING';



