export const GET_STATIONS_BY_REGION_SUCCESS = 'GET_STATIONS_BY_REGION_SUCCESS';
export const GET_STATIONS_BY_REGION_FAILURE = 'GET_STATIONS_BY_REGION_FAILURE';
export const GET_STATIONS_BY_REGION_LOADING = 'GET_STATIONS_BY_REGION_LOADING';

export const GET_VALUES_BY_STATION_METRIC_SUCCESS = "GET_VALUES_BY_STATION_METRIC_SUCCESS";
export const GET_VALUES_BY_STATION_METRIC_FAILURE = "GET_VALUES_BY_STATION_METRIC_FAILURE";
export const GET_VALUES_BY_STATION_METRIC_LOADING = "GET_VALUES_BY_STATION_METRIC_LOADING";


